### ISSUE TITLE
add derivatives check to verification

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/hyrax-migrator#195]
check to see that expected derivatives are present.

**Comment by lsat12357** [comment]
does this belong here? or in OD2

**Comment by luisgreg99** [comment]
Steps for QA:

On OD1:
1. Generate a yml profile for an asset (i.e `fx719p324` -- more examples in https://github.com/OregonDigital/hyrax-migrator/pull/203#issue-404516469)
2. New profile should include a `derivatives_info` key with values for `has_thumbnail`, `page_count`, etc. if available. Sample output: [fx719p324_profile-yml-L15-L24](https://gist.github.com/luisgreg99/1778aed32356bd1c10aca9c8a8a1d0de#file-fx719p324_profile-yml-L15-L24)

On OD2:
1. Transfer new profile (i.e. `fx719p324_profile.yml`) to OD2 staging `/data/tmp/shared/profiles/`
2. Verify derivatives using VerifyDerivativesService. Sample run for pid `fx719p324`:
```
pid = "fx719p324"
original_profile = YAML.load_file(File.join('/data/tmp/shared/profiles', "#{pid}_profile.yml"))
work = Hyrax::Migrator::HyraxCore::Asset.find(pid)
v = Hyrax::Migrator::Services::VerifyDerivativesService.new(work, original_profile)
v.verify
```
verify method should return `[]` if it didn't find any errors, otherwise it should list the errors in the array.

**Comment by lsat12357** [comment]
ran through steps using pid=fx719p37h, works as expected:
irb(main):005:0> v.verify
=> []
