### ISSUE TITLE
Counter for migrated items and original number of works

### ISSUE THREAD

**Issue by luisgreg99** [OregonDigital/hyrax-migrator#211]
This info will be useful during QA to make sure that all works are migrated (check original number of works and OD2 works match after migration).

This info can be retrieved from the original pid list (for original items), and from the hyrax-migrator verification run in OD2 after ingest.

Related to QA (a)(i) step in the: [workflow document](https://docs.google.com/document/d/1AQrPq5FMMW-8Y4rsiZsRxgAfaqe3cp05L4DKy1PCoes/edit#)

**Comment by lsat12357** [comment]
Due to the way we are controlling the workflow this time, i.e.  starting with a pidlist generated by jechol's migration-tool, and all work based on the pidlist, or sub-lists, I think it is unnecessary to try to maintain/track counters during the migration process. I also think it could be fiddly to maintain an accurate count mid-process, eg if we end up re-migrating things instead of updating them, or new assets are added.
we do have as a step in the QA process a comparison of total counts when a collection is finished, which should expose problems that the pidlist will not entirely solve, the case where we lose track of a batch? new items? But I see this as a manual step of generating a new count using the migration-tool on OD1, and comparing it with a front-end count on OD2; i.e. confirming that all assets are not only migrated, but reachable.
