### ISSUE TITLE
Crosswalk Metadata ignore property capability

### ISSUE THREAD

**Issue by revgum** [OregonDigital/hyrax-migrator#50]
Provide the means, in the crosswalk yaml file, to mark a property/predicate as being `ignore: true` .. this would indicate that the code should explicitly not migrate the data. 

The idea here is that all predicates in the original data are accounted for, even if we are making a conscious decision to not migrate the metadata for a predicate.

Thoughts?

**Comment by lsat12357** [comment]
I have some mods to the crosswalk_metadata_service that would allow us to fix things more on the fly; it would handle a predicate that is not on the official od2 pred list either because we're not going to keep it or because there's a mistake and the wrong pred was used.  just pushed the branch up but working on some spec now.
